import type { RowData } from "@tanstack/react-table";

export const columnPickerGroups = [
  { id: "patient", label: "Patient & Demographics" },
  { id: "claim", label: "Claim & Order Details" },
  { id: "diagnoses", label: "Diagnoses & Modifiers" },
  { id: "payer", label: "Payer & Coverage" },
  { id: "provider", label: "Provider & Location Info" },
  { id: "authorization", label: "Authorizations & Compliance" },
  { id: "denials", label: "Denials & Adjustments" },
  { id: "workflow", label: "AR & Workflow" },
  { id: "other", label: "Other" },
] as const;

export type ColumnPickerGroup = (typeof columnPickerGroups)[number]["id"];

// Each entry is one picker column; groups stay together under their own headings.
export const columnPickerLayout = [
  ["patient", "denials", "other"],
  ["claim"],
  ["diagnoses", "authorization"],
  ["payer"],
  ["provider", "workflow"],
] as const satisfies readonly (readonly ColumnPickerGroup[])[];

export const patientColumnDefinitions = [
  {
    key: "patientNumber",
    label: "pt#",
    group: "patient",
    order: 1,
    kind: "text",
  },
  { key: "nm", label: "nm", group: "patient", order: 2, kind: "text" },
  { key: "dob", label: "dob", group: "patient", order: 3, kind: "date" },
  { key: "pt_st", label: "pt_st", group: "patient", order: 4, kind: "text" },
  { key: "ZIP", label: "ZIP", group: "patient", order: 5, kind: "text" },
  { key: "County", label: "County", group: "patient", order: 6, kind: "text" },
  {
    key: "dateOfService",
    label: "dos",
    group: "claim",
    order: 1,
    kind: "date",
  },
  {
    key: "endServiceDate",
    label: "end_service_date:",
    group: "claim",
    order: 2,
    kind: "date",
  },
  { key: "hcpc", label: "hcpc", group: "claim", order: 3, kind: "text" },
  { key: "desc", label: "desc", group: "claim", order: 4, kind: "text" },
  { key: "qty", label: "qty", group: "claim", order: 5, kind: "number" },
  { key: "type", label: "type", group: "claim", order: 6, kind: "text" },
  { key: "sub", label: "sub", group: "claim", order: 7, kind: "text" },
  {
    key: "dispense_type",
    label: "dispense_type",
    group: "claim",
    order: 8,
    kind: "text",
  },
  {
    key: "first ord",
    label: "first ord",
    group: "claim",
    order: 9,
    kind: "text",
  },
  { key: "submit", label: "submit", group: "claim", order: 10, kind: "text" },
  { key: "actions", label: "actions", group: "claim", order: 11, kind: "text" },
  { key: "bllr", label: "bllr", group: "claim", order: 12, kind: "text" },
  { key: "rec#", label: "rec#", group: "claim", order: 13, kind: "text" },
  {
    key: "intake_by",
    label: "intake_by",
    group: "claim",
    order: 14,
    kind: "text",
  },
  { key: "osr", label: "osr", group: "claim", order: 15, kind: "text" },
  { key: "ha0", label: "ha0", group: "claim", order: 16, kind: "text" },
  { key: "pacecom", label: "pacecom", group: "claim", order: 17, kind: "text" },
  { key: "sentDate", label: "sentdt", group: "claim", order: 18, kind: "date" },
  { key: "1500_1", label: "1500_1", group: "claim", order: 19, kind: "text" },
  { key: "1500_2", label: "1500_2", group: "claim", order: 20, kind: "text" },
  { key: "1500_3", label: "1500_3", group: "claim", order: 21, kind: "text" },
  {
    key: "sched_claim_rls_date",
    label: "sched_claim_rls_date",
    group: "claim",
    order: 22,
    kind: "date",
  },
  {
    key: "milk_shortage_bag_sch_rls_date",
    label: "milk_shortage_bag_sch_rls_date",
    group: "claim",
    order: 23,
    kind: "date",
  },
  {
    key: "unreconciled",
    label: "unreconciled",
    group: "claim",
    order: 24,
    kind: "text",
  },
  { key: "lst_icn", label: "lst_icn", group: "claim", order: 25, kind: "text" },
  {
    key: "first ICN",
    label: "first ICN",
    group: "claim",
    order: 26,
    kind: "text",
  },
  {
    key: "icd10_1",
    label: "icd10_1",
    group: "diagnoses",
    order: 1,
    kind: "text",
  },
  {
    key: "icd10_2",
    label: "icd10_2",
    group: "diagnoses",
    order: 2,
    kind: "text",
  },
  {
    key: "icd10_3",
    label: "icd10_3",
    group: "diagnoses",
    order: 3,
    kind: "text",
  },
  {
    key: "icd10_4",
    label: "icd10_4",
    group: "diagnoses",
    order: 4,
    kind: "text",
  },
  {
    key: "icd9_1",
    label: "icd9_1",
    group: "diagnoses",
    order: 5,
    kind: "text",
  },
  {
    key: "icd9_2",
    label: "icd9_2",
    group: "diagnoses",
    order: 6,
    kind: "text",
  },
  {
    key: "icd9_3",
    label: "icd9_3",
    group: "diagnoses",
    order: 7,
    kind: "text",
  },
  {
    key: "icd9_4",
    label: "icd9_4",
    group: "diagnoses",
    order: 8,
    kind: "text",
  },
  { key: "m1", label: "m1", group: "diagnoses", order: 9, kind: "text" },
  { key: "m2", label: "m2", group: "diagnoses", order: 10, kind: "text" },
  { key: "m3", label: "m3", group: "diagnoses", order: 11, kind: "text" },
  { key: "m4", label: "m4", group: "diagnoses", order: 12, kind: "text" },
  { key: "payer", label: "payer", group: "payer", order: 1, kind: "text" },
  {
    key: "payer_type",
    label: "payer_type",
    group: "payer",
    order: 2,
    kind: "text",
  },
  {
    key: "Alpha Prefix",
    label: "Alpha Prefix",
    group: "payer",
    order: 3,
    kind: "text",
  },
  {
    key: "Prefix Payer ID",
    label: "Prefix Payer ID",
    group: "payer",
    order: 4,
    kind: "text",
  },
  {
    key: "Prefix Payor Name",
    label: "Prefix Payor Name",
    group: "payer",
    order: 5,
    kind: "text",
  },
  { key: "pay1", label: "pay1", group: "payer", order: 6, kind: "text" },
  { key: "pay2", label: "pay2", group: "payer", order: 7, kind: "text" },
  { key: "pay3", label: "pay3", group: "payer", order: 8, kind: "text" },
  { key: "pay1id", label: "pay1id", group: "payer", order: 9, kind: "text" },
  { key: "pay2id", label: "pay2id", group: "payer", order: 10, kind: "text" },
  { key: "pay3id", label: "pay3id", group: "payer", order: 11, kind: "text" },
  { key: "1%", label: "1%", group: "payer", order: 12, kind: "number" },
  { key: "2%", label: "2%", group: "payer", order: 13, kind: "number" },
  { key: "3%", label: "3%", group: "payer", order: 14, kind: "number" },
  { key: "1$", label: "1$", group: "payer", order: 15, kind: "number" },
  { key: "2$", label: "2$", group: "payer", order: 16, kind: "number" },
  { key: "3$", label: "3$", group: "payer", order: 17, kind: "number" },
  { key: "hic1", label: "hic1", group: "payer", order: 18, kind: "text" },
  { key: "hic2", label: "hic2", group: "payer", order: 19, kind: "text" },
  { key: "hic3", label: "hic3", group: "payer", order: 20, kind: "text" },
  { key: "grp1", label: "grp1", group: "payer", order: 21, kind: "text" },
  { key: "grp2", label: "grp2", group: "payer", order: 22, kind: "text" },
  { key: "grp3", label: "grp3", group: "payer", order: 23, kind: "text" },
  { key: "ph1", label: "ph1", group: "payer", order: 24, kind: "text" },
  { key: "ph2", label: "ph2", group: "payer", order: 25, kind: "text" },
  { key: "ph3", label: "ph3", group: "payer", order: 26, kind: "text" },
  {
    key: "network_status_lc",
    label: "network_status_lc",
    group: "payer",
    order: 27,
    kind: "text",
  },
  {
    key: "disqualify_wordstring",
    label: "disqualify_wordstring",
    group: "payer",
    order: 28,
    kind: "text",
  },
  { key: "doc", label: "doc", group: "provider", order: 1, kind: "text" },
  { key: "doc_id", label: "doc_id", group: "provider", order: 2, kind: "text" },
  { key: "npi", label: "npi", group: "provider", order: 3, kind: "text" },
  { key: "docph", label: "docph", group: "provider", order: 4, kind: "text" },
  { key: "docfax", label: "docfax", group: "provider", order: 5, kind: "text" },
  {
    key: "originating_provider",
    label: "originating_provider:",
    group: "provider",
    order: 6,
    kind: "text",
  },
  {
    key: "rend_location",
    label: "rend_location",
    group: "provider",
    order: 7,
    kind: "text",
  },
  { key: "lc_id", label: "lc_id", group: "provider", order: 8, kind: "text" },
  {
    key: "lc_name",
    label: "lc_name",
    group: "provider",
    order: 9,
    kind: "text",
  },
  {
    key: "lc_state",
    label: "lc_state",
    group: "provider",
    order: 10,
    kind: "text",
  },
  {
    key: "ancillary_lc_name",
    label: "ancillary_lc_name:",
    group: "provider",
    order: 11,
    kind: "text",
  },
  {
    key: "ancillary_lc_npi",
    label: "ancillary_lc_npi:",
    group: "provider",
    order: 12,
    kind: "text",
  },
  {
    key: "tertiary_lc_name",
    label: "tertiary_lc_name:",
    group: "provider",
    order: 13,
    kind: "text",
  },
  {
    key: "tertiary_lc_npi",
    label: "tertiary_lc_npi:",
    group: "provider",
    order: 14,
    kind: "text",
  },
  {
    key: "qrt_lc_id",
    label: "qrt_lc_id",
    group: "provider",
    order: 15,
    kind: "text",
  },
  {
    key: "qrt_lc_name",
    label: "qrt_lc_name:",
    group: "provider",
    order: 16,
    kind: "text",
  },
  {
    key: "qrt_lc_npi",
    label: "qrt_lc_npi:",
    group: "provider",
    order: 17,
    kind: "text",
  },
  { key: "pa1", label: "pa1", group: "authorization", order: 1, kind: "text" },
  {
    key: "paexp",
    label: "paexp",
    group: "authorization",
    order: 2,
    kind: "date",
  },
  {
    key: "poexp",
    label: "poexp",
    group: "authorization",
    order: 3,
    kind: "date",
  },
  { key: "pa?", label: "pa?", group: "authorization", order: 4, kind: "text" },
  {
    key: "rlsdt",
    label: "rlsdt",
    group: "authorization",
    order: 5,
    kind: "date",
  },
  {
    key: "Timely_for_initial_date",
    label: "Timely_for_initial_date",
    group: "authorization",
    order: 6,
    kind: "date",
  },
  {
    key: "timely_for_corrected_date",
    label: "timely_for_corrected_date",
    group: "authorization",
    order: 7,
    kind: "date",
  },
  {
    key: "secondary_timely_filing",
    label: "secondary_timely_filing:",
    group: "authorization",
    order: 8,
    kind: "date",
  },
  {
    key: "f2fCompliant",
    label: "f2fCompliant",
    group: "authorization",
    order: 9,
    kind: "text",
  },
  {
    key: "usageCompliant",
    label: "usageCompliant",
    group: "authorization",
    order: 10,
    kind: "text",
  },
  {
    key: "compliant",
    label: "compliant",
    group: "authorization",
    order: 11,
    kind: "text",
  },
  {
    key: "in_testing_flag",
    label: "in_testing_flag",
    group: "authorization",
    order: 12,
    kind: "text",
  },
  {
    key: "testing_flag",
    label: "testing_flag",
    group: "authorization",
    order: 13,
    kind: "text",
  },
  {
    key: "time_in_session",
    label: "time_in_session",
    group: "authorization",
    order: 14,
    kind: "number",
  },
  {
    key: "occurence_number",
    label: "occurence_number:",
    group: "authorization",
    order: 15,
    kind: "number",
  },
  {
    key: "denialDate",
    label: "denydt",
    group: "denials",
    order: 1,
    kind: "date",
  },
  {
    key: "denialCode",
    label: "denycd",
    group: "denials",
    order: 2,
    kind: "text",
  },
  {
    key: "denialCode2",
    label: "denycd2",
    group: "denials",
    order: 3,
    kind: "text",
  },
  {
    key: "denialCode3",
    label: "denycd3",
    group: "denials",
    order: 4,
    kind: "text",
  },
  {
    key: "first_deny_code",
    label: "first_deny_code:",
    group: "denials",
    order: 5,
    kind: "text",
  },
  {
    key: "first_deny_remark",
    label: "first_deny_remark:",
    group: "denials",
    order: 6,
    kind: "text",
  },
  {
    key: "first_deny_date",
    label: "first_deny_date:",
    group: "denials",
    order: 7,
    kind: "date",
  },
  {
    key: "rej_ct",
    label: "rej_ct",
    group: "denials",
    order: 8,
    kind: "number",
  },
  { key: "rm1", label: "rm1", group: "denials", order: 9, kind: "text" },
  { key: "rm2", label: "rm2", group: "denials", order: 10, kind: "text" },
  { key: "rm3", label: "rm3", group: "denials", order: 11, kind: "text" },
  {
    key: "category",
    label: "category:",
    group: "denials",
    order: 12,
    kind: "text",
  },
  {
    key: "subcategory",
    label: "subcategory:",
    group: "denials",
    order: 13,
    kind: "text",
  },
  {
    key: "red_flag",
    label: "red_flag",
    group: "denials",
    order: 14,
    kind: "text",
  },
  {
    key: "to_write_off",
    label: "to_write_off",
    group: "denials",
    order: 15,
    kind: "number",
  },
  { key: "dup", label: "dup:", group: "denials", order: 16, kind: "text" },
  {
    key: "underpayment_received",
    label: "underpayment_received",
    group: "denials",
    order: 17,
    kind: "number",
  },
  {
    key: "ar_age",
    label: "ar_age",
    group: "workflow",
    order: 1,
    kind: "number",
  },
  {
    key: "ar_age_bucket",
    label: "ar_age_bucket",
    group: "workflow",
    order: 2,
    kind: "text",
  },
  { key: "due_dt", label: "due_dt", group: "workflow", order: 3, kind: "date" },
  { key: "wrkdt", label: "wrkdt", group: "workflow", order: 4, kind: "date" },
  { key: "worked", label: "worked", group: "workflow", order: 5, kind: "text" },
  { key: "note", label: "note", group: "workflow", order: 6, kind: "text" },
  { key: "dtchg", label: "dtchg", group: "workflow", order: 7, kind: "date" },
  { key: "who", label: "who", group: "workflow", order: 8, kind: "text" },
  { key: "remit", label: "remit", group: "workflow", order: 9, kind: "text" },
  { key: "old?", label: "old?", group: "workflow", order: 10, kind: "text" },
  { key: "xmit", label: "xmit", group: "workflow", order: 11, kind: "number" },
  {
    key: "count",
    label: "count",
    group: "workflow",
    order: 12,
    kind: "number",
  },
  {
    key: "e0602_allowed",
    label: "e0602_allowed",
    group: "other",
    order: 1,
    kind: "text",
  },
  {
    key: "e0603_allowed",
    label: "e0603_allowed",
    group: "other",
    order: 2,
    kind: "text",
  },
  {
    key: "e0604_allowed",
    label: "e0604_allowed",
    group: "other",
    order: 3,
    kind: "text",
  },
  {
    key: "brpump_resupply_allowed",
    label: "brpump_resupply_allowed",
    group: "other",
    order: 4,
    kind: "text",
  },
  {
    key: "k1005_allowed",
    label: "k1005_allowed",
    group: "other",
    order: 5,
    kind: "text",
  },
  {
    key: "prefix_e0604_allowed",
    label: "prefix_e0604_allowed",
    group: "other",
    order: 6,
    kind: "text",
  },
  {
    key: "prefix_e0603_allowed",
    label: "prefix_e0603_allowed",
    group: "other",
    order: 7,
    kind: "text",
  },
  {
    key: "prefix_brpump_resupply_allowed",
    label: "prefix_brpump_resupply_allowed",
    group: "other",
    order: 8,
    kind: "text",
  },
  {
    key: "prefix_k1005_allowed",
    label: "prefix_k1005_allowed",
    group: "other",
    order: 9,
    kind: "text",
  },
] as const satisfies readonly {
  key: string;
  label: string;
  group: ColumnPickerGroup;
  order: number;
  kind: "text" | "number" | "date";
}[];

export type PatientColumnKey = (typeof patientColumnDefinitions)[number]["key"];

declare module "@tanstack/react-table" {
  // Declaration merging requires the same generic parameters as TanStack.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface ColumnMeta<TData extends RowData, TValue> {
    picker?: {
      label: string;
      group: ColumnPickerGroup;
      order: number;
    };
  }
}
