export type Patient = {
  id: string;
  payer: string;
  patientNumber: string;
  hcpc: string;
  dateOfService: string;
  endServiceDate: string;
  sentDate: string | null;
  xmit: number | null;
  denialDate: string | null;
  denialCode: string | null;
  denialCode2: string | null;
  denialCode3: string | null;
  rm1: string | null;
  cmn: string | null;
  remit: string | null;
  serviceStatus: string | null;
};

export const patients: Patient[] = [
  {
    id: "sample-row-1",
    payer: "MOLINA SC MEDICAID",
    patientNumber: "1851449",
    hcpc: "A4927",
    dateOfService: "3/13/2026",
    endServiceDate: "3/13/2026",
    sentDate: "5/1/2026",
    xmit: 2,
    denialDate: "5/12/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-2",
    payer: "TEST PAYER A",
    patientNumber: "TEST-002",
    hcpc: "A4351",
    dateOfService: "3/16/2026",
    endServiceDate: "3/16/2026",
    sentDate: "5/2/2026",
    xmit: 1,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-3",
    payer: "TEST PAYER B",
    patientNumber: "TEST-003",
    hcpc: "A4554",
    dateOfService: "3/18/2026",
    endServiceDate: "3/20/2026",
    sentDate: "5/4/2026",
    xmit: 2,
    denialDate: "5/14/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-4",
    payer: "TEST PAYER A",
    patientNumber: "TEST-004",
    hcpc: "E0601",
    dateOfService: "3/23/2026",
    endServiceDate: "3/23/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-5",
    payer: "TEST PAYER C",
    patientNumber: "TEST-005",
    hcpc: "E0603",
    dateOfService: "3/25/2026",
    endServiceDate: "3/27/2026",
    sentDate: "5/6/2026",
    xmit: 3,
    denialDate: "5/18/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-6",
    payer: "TEST PAYER B",
    patientNumber: "TEST-006",
    hcpc: "A7030",
    dateOfService: "3/30/2026",
    endServiceDate: "3/30/2026",
    sentDate: "5/8/2026",
    xmit: 1,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-7",
    payer: "TEST PAYER A",
    patientNumber: "TEST-007",
    hcpc: "A4927",
    dateOfService: "4/1/2026",
    endServiceDate: "4/1/2026",
    sentDate: "5/1/2026",
    xmit: 2,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-8",
    payer: "TEST PAYER B",
    patientNumber: "TEST-008",
    hcpc: "A4351",
    dateOfService: "4/2/2026",
    endServiceDate: "4/2/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-9",
    payer: "TEST PAYER C",
    patientNumber: "TEST-009",
    hcpc: "A4554",
    dateOfService: "4/3/2026",
    endServiceDate: "4/3/2026",
    sentDate: "5/3/2026",
    xmit: 1,
    denialDate: "5/10/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-10",
    payer: "TEST PAYER A",
    patientNumber: "TEST-010",
    hcpc: "E0601",
    dateOfService: "4/4/2026",
    endServiceDate: "4/6/2026",
    sentDate: "5/4/2026",
    xmit: 2,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-11",
    payer: "TEST PAYER B",
    patientNumber: "TEST-011",
    hcpc: "E0603",
    dateOfService: "4/5/2026",
    endServiceDate: "4/5/2026",
    sentDate: "5/5/2026",
    xmit: 3,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-12",
    payer: "TEST PAYER C",
    patientNumber: "TEST-012",
    hcpc: "A7030",
    dateOfService: "4/6/2026",
    endServiceDate: "4/6/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-13",
    payer: "TEST PAYER A",
    patientNumber: "TEST-013",
    hcpc: "A4927",
    dateOfService: "4/7/2026",
    endServiceDate: "4/7/2026",
    sentDate: "5/7/2026",
    xmit: 2,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-14",
    payer: "TEST PAYER B",
    patientNumber: "TEST-014",
    hcpc: "A4351",
    dateOfService: "4/8/2026",
    endServiceDate: "4/8/2026",
    sentDate: "5/8/2026",
    xmit: 3,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-15",
    payer: "TEST PAYER C",
    patientNumber: "TEST-015",
    hcpc: "A4554",
    dateOfService: "4/9/2026",
    endServiceDate: "4/11/2026",
    sentDate: "5/9/2026",
    xmit: 1,
    denialDate: "5/16/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-16",
    payer: "TEST PAYER A",
    patientNumber: "TEST-016",
    hcpc: "E0601",
    dateOfService: "4/10/2026",
    endServiceDate: "4/10/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-17",
    payer: "TEST PAYER B",
    patientNumber: "TEST-017",
    hcpc: "E0603",
    dateOfService: "4/11/2026",
    endServiceDate: "4/11/2026",
    sentDate: "5/11/2026",
    xmit: 3,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-18",
    payer: "TEST PAYER C",
    patientNumber: "TEST-018",
    hcpc: "A7030",
    dateOfService: "4/12/2026",
    endServiceDate: "4/12/2026",
    sentDate: "5/12/2026",
    xmit: 1,
    denialDate: "5/19/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-19",
    payer: "TEST PAYER A",
    patientNumber: "TEST-019",
    hcpc: "A4927",
    dateOfService: "4/13/2026",
    endServiceDate: "4/13/2026",
    sentDate: "5/13/2026",
    xmit: 2,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-20",
    payer: "TEST PAYER B",
    patientNumber: "TEST-020",
    hcpc: "A4351",
    dateOfService: "4/14/2026",
    endServiceDate: "4/16/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-21",
    payer: "TEST PAYER C",
    patientNumber: "TEST-021",
    hcpc: "A4554",
    dateOfService: "4/15/2026",
    endServiceDate: "4/15/2026",
    sentDate: "5/15/2026",
    xmit: 1,
    denialDate: "5/22/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-22",
    payer: "TEST PAYER A",
    patientNumber: "TEST-022",
    hcpc: "E0601",
    dateOfService: "4/16/2026",
    endServiceDate: "4/16/2026",
    sentDate: "5/16/2026",
    xmit: 2,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-23",
    payer: "TEST PAYER B",
    patientNumber: "TEST-023",
    hcpc: "E0603",
    dateOfService: "4/17/2026",
    endServiceDate: "4/17/2026",
    sentDate: "5/17/2026",
    xmit: 3,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-24",
    payer: "TEST PAYER C",
    patientNumber: "TEST-024",
    hcpc: "A7030",
    dateOfService: "4/18/2026",
    endServiceDate: "4/18/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-25",
    payer: "TEST PAYER A",
    patientNumber: "TEST-025",
    hcpc: "A4927",
    dateOfService: "4/19/2026",
    endServiceDate: "4/21/2026",
    sentDate: "5/19/2026",
    xmit: 2,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-26",
    payer: "TEST PAYER B",
    patientNumber: "TEST-026",
    hcpc: "A4351",
    dateOfService: "4/20/2026",
    endServiceDate: "4/20/2026",
    sentDate: "5/20/2026",
    xmit: 3,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-27",
    payer: "TEST PAYER C",
    patientNumber: "TEST-027",
    hcpc: "A4554",
    dateOfService: "4/21/2026",
    endServiceDate: "4/21/2026",
    sentDate: "5/21/2026",
    xmit: 1,
    denialDate: "5/28/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-28",
    payer: "TEST PAYER A",
    patientNumber: "TEST-028",
    hcpc: "E0601",
    dateOfService: "4/22/2026",
    endServiceDate: "4/22/2026",
    sentDate: null,
    xmit: null,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
  {
    id: "sample-row-29",
    payer: "TEST PAYER B",
    patientNumber: "TEST-029",
    hcpc: "E0603",
    dateOfService: "4/23/2026",
    endServiceDate: "4/23/2026",
    sentDate: "5/23/2026",
    xmit: 3,
    denialDate: null,
    denialCode: null,
    denialCode2: null,
    denialCode3: null,
    rm1: null,
    cmn: null,
    remit: null,
    serviceStatus: "S",
  },
  {
    id: "sample-row-30",
    payer: "TEST PAYER C",
    patientNumber: "TEST-030",
    hcpc: "A7030",
    dateOfService: "4/24/2026",
    endServiceDate: "4/26/2026",
    sentDate: "5/24/2026",
    xmit: 1,
    denialDate: "5/31/2026",
    denialCode: "CO22",
    denialCode2: null,
    denialCode3: null,
    rm1: "N479",
    cmn: null,
    remit: null,
    serviceStatus: "U",
  },
];
